* adapted restartJob tool

diff --git a/Scripts/Misc/restartJob b/Scripts/Misc/restartJob
--- a/Scripts/Misc/restartJob
+++ b/Scripts/Misc/restartJob
@@ -37,21 +37,28 @@ fi # if $MAC
 cd "${WORKDIR}"
 CUR_DELT=$(sed -n '/time_step/ s/^\s*time_step\s*=\s*\([0-9]*\).*$/\1/p' namelist.input) # time step
 ERR=$(( ${ERR} + $? )) # capture exit code
-CUR_EPSS=$(sed -n '/epssm/ s/^\s*epssm\s*=\s*\([0-9]\?.[0-9]*\).*$/\1/p' namelist.input) # epssm parameter; one ore zero times: [0-9]\?.5 -> .5 or 0.5
+CUR_EPSS=$(sed -n '/epssm/ s/^\s*epssm\s*=\s*\([0-9]\?.[0-9]*\).*$/\1/p' namelist.input) # epssm parameter; one or zero times: [0-9]\?.5 -> .5 or 0.5
 ERR=$(( ${ERR} + $? )) # capture exit code
+CUR_DAMP=$(sed -n '/dampcoef/ s/^\s*dampcoef\s*=\s*\([0-9]\?.[0-9]*\).*$/\1/p' namelist.input) # dampcoef parameter; one or zero times: [0-9]\?.5 -> .5 or 0.5
+ERR=$(( ${ERR} + $? )) # capture exit code
+CUR_DIFF=$(sed -n '/diff_6th_factor/ s/^\s*diff_6th_factor\s*=\s*\([0-9]\?.[0-9]*\).*$/\1/p' namelist.input) # diff_6th_factor parameter; one or zero times: [0-9]\?.5 -> .5 or 0.5
+ERR=$(( ${ERR} + $? )) # capture exit code
+CUR_SNDT=$(sed -n '/time_step_sound/ s/^\s*time_step_sound\s*=\s*\([0-9]*\).*$/\1/p' namelist.input) # time_step_sound parameter; integer
+ERR=$(( ${ERR} + $? )) # capture exit code
+
 
 ## define new stability parameters
 if [[ "$SIMPLE" == '0' ]]; then
-  if [[ "$CUR_DELT" == '150' ]] && [[ "$CUR_EPSS" == *'.55' ]]; then
-    NEW_DELT='120'; NEW_EPSS='0.75'
-  elif [[ "$CUR_DELT" == '120' ]] && [[ "$CUR_EPSS" == *'.75' ]]; then
-    NEW_DELT='90'; NEW_EPSS='0.85'; NEW_DAMP='0.06'
-  elif [[ "$CUR_DELT" == '90' ]] && [[ "$CUR_EPSS" == *'.85' ]]; then
-    NEW_DELT='60'; NEW_EPSS='0.95'; NEW_DIFF='0.09'; NEW_DAMP='0.09'; NEW_SND='6'
-  elif [[ "$CUR_DELT" == '60' ]] && [[ "$CUR_EPSS" == *'.95' ]]; then
-    NEW_DELT='50'; NEW_EPSS='0.95'; NEW_DIFF='0.12'; NEW_DAMP='0.12'; NEW_SND='8'
-  elif [[ "$CUR_DELT" == '50' ]] && [[ "$CUR_EPSS" == *'.95' ]]; then
-    NEW_DELT='40'; NEW_EPSS='0.95'; NEW_DIFF='0.15'; NEW_DAMP='0.12'; NEW_SND='8'
+  if [[ "$CUR_DELT" == '150' ]]; then #  && [[ "$CUR_EPSS" == *'.55' ]]
+    NEW_DELT='120'; NEW_EPSS='0.75'; NEW_SNDT='5'
+  elif [[ "$CUR_DELT" == '120' ]]; then #  && [[ "$CUR_EPSS" == *'.75' ]]
+    NEW_DELT='90'; NEW_EPSS='0.85'; NEW_DAMP='0.06'; NEW_SNDT='6'
+  elif [[ "$CUR_DELT" == '90' ]]; then #  && [[ "$CUR_EPSS" == *'.85' ]]
+    NEW_DELT='60'; NEW_EPSS='0.95'; NEW_DIFF='0.09'; NEW_DAMP='0.09'; NEW_SNDT='7'
+  elif [[ "$CUR_DELT" == '60' ]]; then #  && [[ "$CUR_EPSS" == *'.95' ]]
+    NEW_DELT='50'; NEW_EPSS='0.95'; NEW_DIFF='0.12'; NEW_DAMP='0.12'; NEW_SNDT='8'
+  elif [[ "$CUR_DELT" == '50' ]]; then #  && [[ "$CUR_EPSS" == *'.95' ]]
+    NEW_DELT='40'; NEW_EPSS='0.95'; NEW_DIFF='0.15'; NEW_DAMP='0.12'; NEW_SNDT='8'
   elif [[ $FORCE != 1 ]]; then
     echo 'Error: No applicable set of parameters found!'
     exit 1
@@ -72,8 +79,8 @@ fi; if [[ -n "${NEW_DAMP}" ]]; then
 fi; if [[ -n "${NEW_DIFF}" ]]; then
   sed -i "/diff_6th_factor/ s/^\s*diff_6th_factor\s*=\s*[0-9]\?.[0-9]*.*$/ diff_6th_factor = ${NEW_DIFF}, ${NEW_DIFF}, ${NEW_DIFF}, ${NEW_DIFF}, ! edited by restart script; original value: ${CUR_DIFF}/" namelist.input    
   ERR=$(( ${ERR} + $? )) # capture exit code
-fi; if [[ -n "${NEW_SND}" ]]; then
-  sed -i "/time_step_sound/ s/^\s*time_step_sound\s*=\s*[0-9]\?.[0-9]*.*$/ time_step_sound = ${NEW_SND}, ${NEW_SND}, ${NEW_SND}, ${NEW_SND}, ! edited by restart script; original value: ${CUR_SND}/" namelist.input    
+fi; if [[ -n "${NEW_SNDT}" ]]; then
+  sed -i "/time_step_sound/ s/^\s*time_step_sound\s*=\s*[0-9]\?.[0-9]*.*$/ time_step_sound = ${NEW_SNDT}, ${NEW_SNDT}, ${NEW_SNDT}, ${NEW_SNDT}, ! edited by restart script; original value: ${CUR_SNDT}/" namelist.input    
   ERR=$(( ${ERR} + $? )) # capture exit code
 fi
 
